-- Script de Corrección de Permisos (RLS)
-- Ejecuta esto en el Editor SQL de Supabase para permitir que el Frontend lea los datos.

-- 1. RECURSOS (Inventario)
ALTER TABLE RECURSOS ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Lectura pública de recursos" ON RECURSOS;
CREATE POLICY "Lectura pública de recursos" ON RECURSOS FOR SELECT USING (true);

-- 2. CATEGORIAS
ALTER TABLE CATEGORIAS ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Lectura pública de categorias" ON CATEGORIAS;
CREATE POLICY "Lectura pública de categorias" ON CATEGORIAS FOR SELECT USING (true);

-- 3. SEDES
ALTER TABLE SEDES ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Lectura pública de sedes" ON SEDES;
CREATE POLICY "Lectura pública de sedes" ON SEDES FOR SELECT USING (true);

-- 4. USUARIOS (Para login)
ALTER TABLE USUARIOS ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Lectura pública de usuarios" ON USUARIOS;
CREATE POLICY "Lectura pública de usuarios" ON USUARIOS FOR SELECT USING (true);

-- 5. ALQUILERES
ALTER TABLE ALQUILERES ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Lectura pública de alquileres" ON ALQUILERES;
CREATE POLICY "Lectura pública de alquileres" ON ALQUILERES FOR SELECT USING (true);

-- 6. ALQUILER_DETALLES
ALTER TABLE ALQUILER_DETALLES ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Lectura pública de detalles" ON ALQUILER_DETALLES;
CREATE POLICY "Lectura pública de detalles" ON ALQUILER_DETALLES FOR SELECT USING (true);

-- 7. CONFIGURACION
ALTER TABLE CONFIGURACION ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Lectura pública de configuracion" ON CONFIGURACION;
CREATE POLICY "Lectura pública de configuracion" ON CONFIGURACION FOR SELECT USING (true);

-- 8. PROMOCIONES
ALTER TABLE PROMOCIONES ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Lectura pública de promociones" ON PROMOCIONES;
CREATE POLICY "Lectura pública de promociones" ON PROMOCIONES FOR SELECT USING (true);

-- 9. MANTENIMIENTOS
ALTER TABLE MANTENIMIENTOS ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Lectura pública de mantenimientos" ON MANTENIMIENTOS;
CREATE POLICY "Lectura pública de mantenimientos" ON MANTENIMIENTOS FOR SELECT USING (true);

-- 10. ESTADOS_ALQUILER
ALTER TABLE ESTADOS_ALQUILER ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Lectura pública de estados" ON ESTADOS_ALQUILER;
CREATE POLICY "Lectura pública de estados" ON ESTADOS_ALQUILER FOR SELECT USING (true);

-- 11. ROLES
ALTER TABLE ROLES ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Lectura pública de roles" ON ROLES;
CREATE POLICY "Lectura pública de roles" ON ROLES FOR SELECT USING (true);

-- 12. SERVICIOS
ALTER TABLE SERVICIOS ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Lectura pública de servicios" ON SERVICIOS;
CREATE POLICY "Lectura pública de servicios" ON SERVICIOS FOR SELECT USING (true);

-- 13. METODOS_PAGO
ALTER TABLE METODOS_PAGO ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Lectura pública de metodos_pago" ON METODOS_PAGO;
CREATE POLICY "Lectura pública de metodos_pago" ON METODOS_PAGO FOR SELECT USING (true);
