-- 10_cleanup_test_data.sql
-- Cleanup test data as requested.

-- 1. Delete test users (This will trigger Audit logs!)
DELETE FROM USUARIOS
WHERE
    email ILIKE '%prueba%'
    OR nombre ILIKE '%prueba%';

-- 2. Clean up operational tables and audit (TRUNCATE removes all rows and resets identity)
-- WE DO THIS AFTER DELETING USERS so that the audit logs generated by deletion are also cleared
-- and the sequence is safely reset without conflict.
TRUNCATE TABLE ALQUILER_DETALLES,
ALQUILERES,
MANTENIMIENTOS,
AUDITORIA
RESTART IDENTITY CASCADE;

-- 3. Ensure sequences are reset (Redundant if RESTART IDENTITY works, but safe now that tables are empty)
ALTER SEQUENCE IF EXISTS alquiler_detalles_id_seq RESTART WITH 1;

ALTER SEQUENCE IF EXISTS mantenimientos_id_seq RESTART WITH 1;

ALTER SEQUENCE IF EXISTS auditoria_id_seq RESTART WITH 1;