-- RESTORE LEGACY SCHEMA (Monolithic Users Table)
-- 1. Drop the 'Split' tables I created in the previous attempt
DROP TABLE IF EXISTS perfiles_admins CASCADE;

DROP TABLE IF EXISTS perfiles_vendedores CASCADE;

DROP TABLE IF EXISTS perfiles_mecanicos CASCADE;

DROP TABLE IF EXISTS perfiles_turistas CASCADE;

DROP TABLE IF EXISTS soporte_tickets CASCADE;

DROP TABLE IF EXISTS mensajes CASCADE;

DROP TABLE IF EXISTS contactos_usuario CASCADE;

DROP TABLE IF EXISTS recursos CASCADE;

DROP TABLE IF EXISTS alquiler_detalles CASCADE;

DROP TABLE IF EXISTS alquileres CASCADE;

-- 2. APPLY USER PROVIDED SCHEMA (Context-Aware)

-- Function required for UUIDs
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ROLES (Base tables first)
CREATE TABLE IF NOT EXISTS public.roles (
    id text NOT NULL PRIMARY KEY,
    nombre text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.sedes (
  id text NOT NULL PRIMARY KEY,
  nombre text NOT NULL,
  direccion text NOT NULL,
  descripcion text,
  imagen text,
  horario text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  telefono text,
  correo_contacto text,
  mapa_url text,
  hora_apertura time without time zone DEFAULT '08:00:00'::time without time zone,
  hora_cierre time without time zone DEFAULT '18:00:00'::time without time zone
);

CREATE TABLE IF NOT EXISTS public.categorias (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.servicios (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.metodos_pago (
    id text NOT NULL PRIMARY KEY,
    nombre text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.estados_alquiler (
  id text NOT NULL PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  es_final text DEFAULT 'false'::text
);

CREATE TABLE IF NOT EXISTS public.usuarios (
  id text NOT NULL DEFAULT (uuid_generate_v4())::text PRIMARY KEY,
  email text NOT NULL UNIQUE CHECK (email IS NULL OR email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  password text NOT NULL,
  rol_id text NOT NULL REFERENCES public.roles(id),
  nombre text NOT NULL,
  telefono text,
  tipo_documento text,
  numero_documento text,
  fecha_nacimiento date,
  licencia_conducir boolean DEFAULT false,
  nacionalidad text,
  direccion text,
  contacto_emergencia text CHECK (contacto_emergencia IS NULL OR length(contacto_emergencia) >= 5),
  anexo text,
  oficina text,
  codigo_empleado text,
  turno text,
  especialidad text,
  experiencia text,
  sede_id text REFERENCES public.sedes(id),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  pregunta_secreta text,
  respuesta_secreta text,
  activo boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.contactos_usuario (
    id uuid NOT NULL DEFAULT gen_random_uuid () PRIMARY KEY,
    usuario_id text NOT NULL REFERENCES public.usuarios (id),
    nombre character varying NOT NULL,
    telefono character varying NOT NULL,
    relacion character varying,
    created_at timestamp
    with
        time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.recursos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sede_id text NOT NULL REFERENCES public.sedes(id),
  nombre text NOT NULL,
  categoria_id integer NOT NULL REFERENCES public.categorias(id),
  precio_por_hora numeric NOT NULL CHECK (precio_por_hora >= 0::numeric),
  stock_total integer NOT NULL DEFAULT 0 CHECK (stock_total >= 0),
  imagen text,
  descripcion text,
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  guia_seguridad text
);

CREATE TABLE IF NOT EXISTS public.soporte_tickets (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id text REFERENCES public.usuarios(id),
  asunto text NOT NULL,
  mensaje text NOT NULL,
  estado text NOT NULL DEFAULT 'pendiente'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mensajes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  remitente_id text REFERENCES public.usuarios(id),
  destinatario_id text NOT NULL REFERENCES public.usuarios(id),
  asunto text,
  contenido text NOT NULL,
  leido boolean DEFAULT false,
  tipo text DEFAULT 'mensaje'::text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.alquileres (
  id text NOT NULL DEFAULT (uuid_generate_v4())::text PRIMARY KEY,
  codigo_reserva text DEFAULT SUBSTRING((uuid_generate_v4())::text FROM 1 FOR 8) UNIQUE,
  cliente_id text NOT NULL REFERENCES public.usuarios(id),
  vendedor_id text REFERENCES public.usuarios(id),
  sede_id text NOT NULL REFERENCES public.sedes(id),
  fecha_inicio timestamp with time zone NOT NULL,
  fecha_fin_estimada timestamp with time zone NOT NULL,
  fecha_devolucion_real timestamp with time zone,
  total_bruto numeric NOT NULL DEFAULT 0,
  descuento_promociones numeric DEFAULT 0,
  total_servicio numeric NOT NULL,
  garantia numeric NOT NULL,
  total_final numeric NOT NULL CHECK (total_final >= 0::numeric),
  monto_pagado numeric NOT NULL DEFAULT 0,
  saldo_pendiente numeric NOT NULL DEFAULT 0,
  tipo_reserva text NOT NULL CHECK (tipo_reserva = ANY (ARRAY['inmediata'::text, 'anticipada'::text])),
  metodo_pago_id text NOT NULL REFERENCES public.metodos_pago(id),
  tipo_comprobante text NOT NULL CHECK (tipo_comprobante = ANY (ARRAY['boleta'::text, 'factura'::text])),
  datos_factura jsonb,
  estado_id text NOT NULL DEFAULT 'pendiente'::text REFERENCES public.estados_alquiler(id),
  penalizacion numeric DEFAULT 0,
  notas text,
  contrato_firmado boolean DEFAULT false,
  fecha_firma timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  entregado_por text REFERENCES public.usuarios(id),
  recibido_por text REFERENCES public.usuarios(id),
  codigo_cupon text,
  metodo_pago_detalle text
);

CREATE TABLE IF NOT EXISTS public.alquiler_detalles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alquiler_id text NOT NULL REFERENCES public.alquileres(id),
  recurso_id integer NOT NULL REFERENCES public.recursos(id),
  cantidad integer NOT NULL CHECK (cantidad > 0),
  horas integer NOT NULL CHECK (horas > 0),
  precio_unitario numeric NOT NULL CHECK (precio_unitario >= 0::numeric),
  subtotal numeric NOT NULL
);

-- Enable RLS (Default to open/safe)
ALTER TABLE usuarios DISABLE ROW LEVEL SECURITY;

ALTER TABLE recursos DISABLE ROW LEVEL SECURITY;

ALTER TABLE alquileres DISABLE ROW LEVEL SECURITY;

ALTER TABLE contactos_usuario DISABLE ROW LEVEL SECURITY;

NOTIFY pgrst, 'reload config';